### ISSUE TITLE
Items project

### ISSUE THREAD

**Issue by dalexandrov** [microstream-one/examples#22]
Hello,
when I run Items example and type `a something`

I receive:

`a something
Item added
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at one.microstream.sampler.items.Main.command(Main.java:50)
	at one.microstream.sampler.items.Main.command(Main.java:64)
	at one.microstream.sampler.items.Main.start(Main.java:26)
	at one.microstream.sampler.items.Main.main(Main.java:21)`

**Comment by fh-ms** [comment]
PicoCLI is now used as command line interface instead of java.util.Scanner.
